name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read
  pull-requests: write
  # Add more permissions as needed (e.g., issues, workflows, etc.)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # or your required Java version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew clean test
        continue-on-error: true # Ensures further steps like screenshots are executed

      - name: Capture failed tests screenshots
        if: failure()
        run: |

      - name: Upload screenshots (if any)
        if: failure() # Only upload if tests failed
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: path/to/screenshots/folder

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v3
        with:
           name: cucumber-reports
           path: target/*

     # Step 6: Deploy Cucumber report to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages

      - name: Post results in the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflow } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            core.info(`Tests run with conclusion: ${workflow.conclusion}`);
