name: Run Cucumber Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]  # Matrix strategy for cross-browser testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up ChromeDriver
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1

      - name: Set up FirefoxDriver
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew clean test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: build/reports/cucumber/

      - name: Post results in the PR
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const results = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            core.info(`Tests run with status: ${results.conclusion}`);
